Additions to 5x5 scrambles
thewca/wca-regulations pull request #1069
Opened 2022-10-25 20:10 UTC by Rouxles

This is something that I think should be implemented. This, however, is somewhat more controversial IMO (but I do stand firm that 5BLD must be scrambled correctly)

2022-10-25 20:12 UTC, JoaoViniciusSantos approved these changes

2022-10-25 20:14 UTC, andrewtyberg approved these changes

2022-10-25 20:38 UTC, Nevseros requested changes

2022-10-25 20:38 UTC, Nevseros commented on wca-guidelines.md
> +- 4g1++) [RECOMMENDATION] A Delegate should only use discretion for allowing incorrect scramble states if it is necessary for the event to be held.
Must be `A WCA Delegate`, not just `A Delegate`.

2022-10-25 22:15 UTC, Rouxles commented on wca-guidelines.md
> +- 4g1++) [RECOMMENDATION] A Delegate should only use discretion for allowing incorrect scramble states if it is necessary for the event to be held.
```suggestion
- 4g1++) [RECOMMENDATION] A WCA Delegate should only use discretion for allowing incorrect scramble states if it is necessary for the event to be held.
```

2022-10-26 14:56 UTC, CelineTrammi approved these changes

2022-10-29 11:17 UTC, Nevseros approved these changes

2022-11-10 17:18 UTC, Rouxles commented on wca-guidelines.md
> +- 4g1+) [CLARIFICATION] 5x5x5 Blindfolded scrambles must be scrambled correctly
```suggestion
- 4g1+) [CLARIFICATION] 5x5x5 Blindfolded scrambles must be scrambled correctly.
```

2022-11-10 17:19 UTC, Rouxles commented on wca-guidelines.md
> +- 4g1+) [CLARIFICATION] 5x5x5 Blindfolded scrambles must be scrambled correctly
```suggestion
- 4g1+) [REMINDER] 5x5x5 Blindfolded scrambles must be scrambled correctly
```

2022-11-10 17:20 UTC, Rouxles commented on wca-guidelines.md
> +- 4g1+) [CLARIFICATION] 5x5x5 Blindfolded scrambles must be scrambled correctly
could also be clarification @lgarron what do you think?

2022-11-11 08:32 UTC, lgarron commented on wca-guidelines.md
> +- 4g1+) [CLARIFICATION] 5x5x5 Blindfolded scrambles must be scrambled correctly
I think we should still hold off on this change at all until we've figured out a way to address record mis-scrambles (e.g. by requiring scrambler signature and/or an extra checker for it) that can be applied to 5x5x5.

2022-12-01 08:02 UTC, Rouxles commented
Will not be implemented for now - is still in consideration for a later update.

2022-12-01 08:02 UTC, closed without merging