Allowing Clock Logos
thewca/wca-regulations pull request #1072
Opened 2022-10-29 15:16 UTC by JoaoViniciusSantos

Adding 3l1c so now Clocks are officially allowed to have logos.

2022-10-29 15:34 UTC, Nevseros requested changes

2022-10-29 15:34 UTC, Nevseros commented on wca-regulations.md
> +        - 3l1c) For Clock, the logo must be anywhere on the puzzle, as long as the clock faces remain uncovered.
`Must` $\to$ `may`.

Mybe also worth adding `inner` to make it match the use from [10h1](https://www.worldcubeassociation.org/regulations/#10h1)?

2022-10-29 16:17 UTC, Nevseros approved these changes

2022-10-30 02:07 UTC, Nanush7 approved these changes

2022-11-10 16:56 UTC, Rouxles requested changes

2022-11-10 16:56 UTC, Rouxles commented on wca-regulations.md
> +        - 3l1c) For Clock, the logo may be anywhere on the puzzle, as long as the inner clock faces remain uncovered.
See #1076

2022-12-02 01:03 UTC, Rouxles commented
#1076

2022-12-02 01:03 UTC, closed without merging