Bluetooth cubes forbiddance clarification
thewca/wca-regulations pull request #837
Opened 2019-10-01 19:44 UTC by Ivan-Brigidano

See #665 and #783 
I think this way is the most logical way to clarify that this cubes aren't allowed

2019-10-01 21:24 UTC, Ivan-Brigidano commented
Maybe it’s better to incloude it into 3k)?

2019-10-02 00:18 UTC, hanwu85 commented
I don't think it's necessary to included it in 3k, they are talking about different aspect of things.
Regarding travis error, there is a white space at line 118.

2019-10-02 01:07 UTC, lgarron requested changes

2019-10-02 01:07 UTC, lgarron commented on wca-guidelines.md
> +- 2i+++) [REMINDER] Bluetooth puzzles are considered electric devices.
Small tweak:

```suggestion
- 2i+++) [REMINDER] Bluetooth puzzles are considered electronic devices.
```

2019-10-02 01:07 UTC, lgarron commented on wca-regulations.md
> +    - 3a4) Puzzles must not have bluetooth and/or wi-fi functions (see [Regulation 2i](regulations:regulation:2i)).
I'd do something like this:

```suggestion
    - 3a4) Puzzles must not have electronic components (e.g. Bluetooth or Wi-Fi capabilities, motors, sensors, lights). See [Regulation 2i](regulations:regulation:2i).
```

2019-10-02 01:08 UTC, lgarron commented
Thanks for submitting this!

2019-10-03 07:14 UTC, lgarron approved these changes

2019-10-05 14:03 UTC, merged