Extra attempt reason recording
thewca/wca-regulations pull request #849
Opened 2019-10-08 00:41 UTC by hanwu85

Recommending the delegates to record the reasons for extra attempts.

2019-10-08 00:42 UTC, maconard commented
We always record the reasons for extras on the back of the affected scorecard at Midwest comps :)

2019-10-08 00:43 UTC, xsrvmy commented
> We always record the reasons for extras on the back of the affected scorecard at Midwest comps :)

I have the same experience here in Ontario.

2019-10-08 05:55 UTC, Ivan-Brigidano requested changes

2019-10-08 05:55 UTC, Ivan-Brigidano commented on wca-guidelines.md
> +- 11e++) [RECOMMENDATION] The deleagte who grants the extra attempt should record the reason(s) for the extra attempt (e.g. on the back of the score sheet).
```suggestion
- 11e++) [RECOMMENDATION] The WCA Delegate should record the reason(s) for the extra attempt (e.g. on the back of the score sheet).
```

2019-10-08 05:57 UTC, Ivan-Brigidano commented
@maconard that's a good habit!
@hanwu85 important typo: ~delegate~ --> WCA Delegate. We must use an [uniform style](https://github.com/thewca/wca-regulations/blob/draft/style-guide.md).

2019-10-08 06:36 UTC, hanwu85 commented
Thanks!  I just roughly checked the original document.
E2c2++ also needs to be updated to **the WCA Delegat**

2019-10-08 07:29 UTC, Ivan-Brigidano approved these changes

2019-11-30 14:12 UTC, lgarron approved these changes

2019-11-30 14:12 UTC, merged