Change "combined rounds" to "cutoff rounds". Closes #543.
thewca/wca-regulations pull request #889
Opened 2019-12-01 00:07 UTC by lgarron

2019-12-01 09:05 UTC, Ivan-Brigidano requested changes
You forgot to change it in regulation 9o).

2019-12-02 04:15 UTC, Rouxles commented
Can't seem to find the PR from here, is the link dead?

2019-12-02 05:10 UTC, lgarron commented
> Can't seem to find the PR from here, is the link dead?

Hmm, https://github.com/thewca/wca-regulations/pull/889/files should show it.

2019-12-02 05:36 UTC, Rouxles approved these changes

2019-12-02 17:56 UTC, Ivan-Brigidano approved these changes

2019-12-02 17:56 UTC, merged